name: flutter_turnstile
description: A Flutter package to integrate turnstile functionality for secure access control systems.
version: 1.1.3
repository: https://github.com/chen-golang/flutter_turnstile

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.0
  webview_flutter_android: ">=3.12.0 <5.0.0"
  webview_flutter_web: ^0.2.3+4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/flutter_turnstile/data/trunstile.html